#!/usr/bin/env php

<?php

//const SYS_ROOT = __DIR__ . DIRECTORY_SEPARATOR .'app';
const SYS_ROOT = __DIR__  . '/../../../app';
const ROOT = __DIR__ . '/../../..';

//require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/../../autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;

$application = new Application();

$finder = new Finder();
$finder->files()->name('*Command.php')->in(__DIR__.'/console/commands');
foreach ($finder as $file) {
    $clsName = rtrim($file->getFilename(), '.php');
    require_once ($file->getRealPath());
    //加载命令
    $application->add(new $clsName);
}
try {
    $application->run();
} catch (Exception $e) {
}
